global:
  resolve_timeout: 5m

route:
  receiver: 'dev-log'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'dev-log'
    webhook_configs:
      - url: "http://localhost:5000/alert"  # Change to email/webhook if needed
