global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  # ==================================================
  # FastAPI Inference
  # ==================================================
  - job_name: fastapi-inference
    metrics_path: /metrics
    static_configs:
      - targets:
          - fastapi-inference:8000

  # ==================================================
  # Alert Service (custom metrics)
  # ==================================================
  - job_name: alert-service
    static_configs:
      - targets:
          - alert-service:9101

  # ==================================================
  # MLflow (optional â€“ only if /metrics exposed)
  # ==================================================
  - job_name: mlflow
    static_configs:
      - targets:
          - mlflow:5000

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml
